### ISSUE TITLE
Equivalent of `array_init` ?

### ISSUE THREAD

**Issue by rambip** [usbalbin/iter_fixed#15]
I used the array_init crate for my last project, and I was wondering how to implement that behavior in this crate.

The more idiomatic way would probably be to take a range, convert it into a fixed iterator, and map it but I don't know if there is a better way.

How could this pattern be implemented/included in your crate ?

**Comment by usbalbin** [comment]
The problem with ranges is that their length is not known at compile time and thus they can not safely implement `IntoIteratorFixed`. However I do believe something like (not tested):
```rust
let res: [i32; 4] = array_init::from_iter(0..4).unwrap();
assert_eq!(res, [0, 1, 2, 3]);
```

But for iter_fixed perhaps something like #16 would be useful?

**Comment by rambip** [comment]
That's exactly what I wanted !
Otherwise, would it be possible to create a fixedRange type that would be compatible with this crate ?

**Comment by usbalbin** [comment]
Sure, what about something like this?

```rust
use std::ops::Range;
use iter_fixed::{IntoIteratorFixed, IteratorFixed};

// NOTE: The const arguments are START and COUNT unlike Range
// which is on the form first..end . This is needed to avoid requiring the
// unstable feature `const_evaluatable_checked`
#[derive(Clone, Copy)]
struct FixedRange<const START: usize, const COUNT: usize>;

unsafe impl<const START: usize, const COUNT: usize> IntoIteratorFixed<COUNT>
    for FixedRange<START, COUNT>
{
    type Item = usize;

    type IntoIter = Range<usize>;

    fn into_iter_fixed(self) -> iter_fixed::IteratorFixed<Self::IntoIter, COUNT>{
        // Safety: START..(START + COUNT) will always yield COUNT values
        unsafe { IteratorFixed::from_iter(START..(START + COUNT)) }
    }
}

fn main() {
    let a: [usize; 3] = FixedRange::<1, 3>.into_iter_fixed().collect();

    assert_eq!(a, [1, 2, 3]);
}
```

However if `IntoIteratorFixed` is the only reason for the type then perhaps something like:

```rust
fn fixed_range<const START: usize, const COUNT: usize>() -> IteratorFixed<Range<usize>, COUNT> {
    // Safety: START..(START + COUNT) will always yield COUNT values
    unsafe { IteratorFixed::from_iter(START..(START + COUNT)) }
}

let b: [usize; 3] = fixed_range::<1, 3>().collect();
assert_eq!(b, [1, 2, 3]);
```
would be more convenient

---

And to be clear, there is always the escape hatch,  `unsafe IteratorFixed::from_iter` which can be used for any iterator. However the caller is responsible for guaranteeing that the iterator will yeild N items
